### ISSUE TITLE
Crash with XML parsing error

### ISSUE THREAD

**Issue by sirnacnud** [kateinoigakukun/IBLinter#15] opened 2018-01-22 10:22 UTC
I tried linting a project and the tool crashes with the below error. The XIB file it is failing on is part of CocoaLumberjack and can be found [here](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Framework/FmwkTest/en.lproj/MainMenu.xib).

```
Fatal error: parse error /Users/dcunningham/Source/ios/Carthage/Checkouts/CocoaLumberjack/Framework/FmwkTest/en.lproj/MainMenu.xib: XML Element Error: Incorrect key ["document"]: file /private/tmp/iblinter-20180122-98170-1yh0fk4/IBLinter-0.1.5/Sources/IBLinterCore/XibFile.swift, line 37
Illegal instruction: 4
```

**Comment by kateinoigakukun** [comment] 2018-01-23 09:49
Thank you for your report.

This error is seemed to be caused by `AppKit xib`. IBLinter only targets `UIKit xib`.
So I'll make PR to skip `AppKit xib` file.

**Comment by piotr-tobolski** [comment] 2018-01-24 16:26
Nope, I was getting this error when using UIKit xib. But it was very old file saved in some old Xcode format. Just entering this xib and saving it fixed this issue (and changed almost everything in this file). I am working in an old project and this xib dates probably back to iOS 6 and wasn't touched since. This is just table view cell with empty view and some constraints: [EmptyTableViewCell.xib.zip](https://github.com/kateinoigakukun/IBLinter/files/1660615/EmptyTableViewCell.xib.zip)

**Comment by alakoring** [comment] 2018-01-26 17:21
My #16 is fixed now.

**Closed** 2018-01-29 00:26 UTC
